import re

def remove_cn_punctuation(text):
    """Remove all Chinese and English punctuation"""
    cn_punc = '，。！？、；：""''（）【】《》—…·'
    for p in cn_punc:
        text = text.replace(p, '')
    en_punc = ',.!?;:\'"()[]{}-'
    # Only remove trailing punctuation
    return text

# Read source SRT
with open(r'E:\视频脚本\进行中\04-AI替你工作8小时你的工资涨还是跌\AI工作8小时.srt', 'r', encoding='utf-8') as f:
    content = f.read()

# Parse SRT entries
pattern = r'(\d+)\n(\d{2}:\d{2}:\d{2},\d{3} --> \d{2}:\d{2}:\d{2},\d{3})\n(.+?)(?=\n\n|\Z)'
entries = re.findall(pattern, content, re.DOTALL)

print(f"Found {len(entries)} entries")

# Translation mapping
translations = {
    "我先给你看一个数字": "Let me show you a number first",
    "2025年": "2025",
    "斯坦福大学发了一份报告": "Stanford University released a report",
    "报告里有一组数据让所有人沉默了": "A set of data in that report silenced everyone",
    "22到25岁的年轻程序员": "Young programmers aged 22 to 25",
    "过去一年的就业率": "Their employment rate over the past year",
    "下跌了13%": "Dropped by 13%",
    "而40岁以上的资深程序员": "But senior programmers over 40",
    "工资反而涨了8%": "Saw their salaries go up by 8%",
    "为什么": "Why",
    "因为AI替代了那些刚学会写代码的人": "Because AI replaced those who just learned to code",
    "但让那些知道为什么这样写代码的人": "But made those who know why code is written this way",
    "更值钱了": "More valuable",
    "你可能在想": "You might be thinking",
    "这是程序员的事": "This is a programmer's problem",
    "跟我没关系": "None of my business",
    "错": "Wrong",
    "OpenAI内部有个推算": "Inside OpenAI there's an estimate",
    "到2030年": "By 2030",
    "全球60%的白领工作会被AI重塑": "60% of white-collar jobs worldwide will be reshaped by AI",
    "注意": "Note",
    "是重塑": "Reshaped",
    "不是消失": "Not eliminated",
    "重塑的意思是": "Reshaped means",
    "同样一份工作": "The same job",
    "会变成两批人": "Will split into two groups of people",
    "一批人工资暴涨": "One group sees massive salary increases",
    "另一批人直接归零": "The other group goes straight to zero",
    "而你属于哪一批": "And which group you belong to",
    "今天就在被决定": "Is being decided today",
    "真相是": "The truth is",
    "AI不是你的对手": "AI is not your opponent",
    "它是个放大器": "It's an amplifier",
    "它把勤奋的人放大成不可替代": "It amplifies hardworking people into irreplaceable ones",
    "把听话的人放大成可以替换": "It amplifies obedient people into replaceable ones",
    "今天我用10分钟": "Today I'll spend 10 minutes",
    "告诉你这个放大器到底怎么运作": "Telling you how this amplifier actually works",
    "以及怎么把自己放到被涨薪那一边": "And how to put yourself on the side that gets raises",
    "听完这条视频": "After watching this video",
    "你今晚的睡眠质量可能会跟昨天完全不一样": "Your sleep quality tonight might be completely different from last night",
    "回到正题": "Back to the point",
    "200年前": "200 years ago",
    "英国发生过一件事": "Something happened in Britain",
    "1811年": "In 1811",
    "纺织工人组织起来": "Textile workers organized",
    "开始砸纺织机": "And started smashing textile machines",
    "他们的领袖叫卢德": "Their leader was named Ludd",
    "所以这场运动叫卢德运动": "So this movement was called the Luddite movement",
    "为什么砸机器": "Why smash machines",
    "因为蒸汽纺织机一开": "Because once the steam-powered loom started",
    "10个工人的活": "The work of 10 workers",
    "1个人就能干完": "Could be done by just 1 person",
    "工人觉得": "Workers felt",
    "机器抢了我们的饭碗": "Machines are stealing our jobs",
    "但你猜200年后回头看": "But guess what happened when you look back 200 years later",
    "这事儿是什么结果": "What was the result",
    "英国纺织业的工人数": "The number of textile workers in Britain",
    "比1811年多了20倍": "Was 20 times more than in 1811",
    "工资呢": "And wages",
    "涨了40倍": "Went up 40 times",
    "机器没抢走工作": "Machines didn't steal jobs",
    "反而创造了更多工作": "They actually created more jobs",
    "经济学家把这个错误的预判": "Economists call this wrong prediction",
    "叫做卢德谬误": "The Luddite Fallacy",
    "它是说": "It means",
    "人类总是高估短期的破坏": "Humans always overestimate short-term disruption",
    "低估长期的创造": "And underestimate long-term creation",
    "我再给你一组数据": "Let me give you another set of data",
    "1900年的时候": "In 1900",
    "美国41%的劳动人口是农民": "41% of the US workforce were farmers",
    "100年之后": "100 years later",
    "这个比例只剩2%": "That ratio was down to just 2%",
    "99%的农民去哪了": "Where did 99% of the farmers go",
    "他们的孩子": "Their children",
    "孙子": "Grandchildren",
    "变成了汽车工程师": "Became automotive engineers",
    "程序员": "Programmers",
    "设计师": "Designers",
    "医生": "Doctors",
    "老师": "Teachers",
    "整个社会的财富水平": "The overall wealth level of society",
    "比1900年涨了20倍": "Went up 20 times compared to 1900",
    "这就是技术革命的真实历史": "This is the real history of technological revolutions",
    "它从来不是消灭工作": "It never eliminates jobs entirely",
    "是消灭某一类工作": "It eliminates a certain type of job",
    "然后创造另一类更复杂的工作": "Then creates a more complex type of job",
    "但注意听": "But listen carefully",
    "消灭和创造之间": "Between elimination and creation",
    "有一个时间差": "There's a time gap",
    "这个时间差": "This time gap",
    "可能是10年": "Could be 10 years",
    "也可能是30年": "Or even 30 years",
    "死在这个时间差里的人": "People who die in this time gap",
    "就成了卢德运动里那批砸机器的工人": "Become those machine-smashing workers in the Luddite movement",
    "你今天面对AI": "You today facing AI",
    "也站在同样的时间差里": "Are standing in the exact same time gap",
    "问题不是会不会有新工作": "The question is not whether new jobs will appear",
    "是": "It's whether",
    "你能不能熬到新工作出现的那一天": "You can survive until the day those new jobs arrive",
    "注意听": "Listen carefully",
    "这里讲一个比卢德谬误更扎心的概念": "Here's a concept that hits harder than the Luddite Fallacy",
    "经济学里把技术对工人的影响": "In economics the impact of technology on workers",
    "分成两种": "Is divided into two types",
    "第一种叫替代效应": "The first is called the substitution effect",
    "机器能干的事": "What machines can do",
    "工人就别干了": "Workers shouldn't bother doing",
    "直接被替换掉": "You get directly replaced",
    "100年前替代了纺织工人": "100 years ago it replaced textile workers",
    "50年前替代了电话接线员": "50 years ago it replaced telephone operators",
    "10年前替代了银行柜员": "10 years ago it replaced bank tellers",
    "明天替代谁": "Who will it replace tomorrow",
    "答案就在你周围": "The answer is all around you",
    "初级客服": "Junior customer service",
    "初级文案": "Junior copywriters",
    "初级设计师": "Junior designers",
    "初级翻译": "Junior translators",
    "入门程序员": "Entry-level programmers",
    "报税员": "Tax preparers",
    "低级会计": "Junior accountants",
    "合同审核员": "Contract reviewers",
    "初级数据分析师": "Junior data analysts",
    "凡是规则清晰": "Any job with clear rules",
    "重复执行": "Repetitive execution",
    "不需要复杂判断的工作": "That doesn't need complex judgment",
    "AI在3年内会全部替代掉": "AI will replace all of them within 3 years",
    "第二种叫互补效应": "The second is called the complementarity effect",
    "机器干了基础活": "Machines handle the basic work",
    "反而让人能干更高阶的事": "Which actually lets people do higher-level work",
    "举个例子": "For example",
    "10年前": "10 years ago",
    "一个普通设计师每天的工作是什么": "What was a regular designer's daily work",
    "切图": "Slicing images",
    "调间距": "Adjusting spacing",
    "做banner": "Making banners",
    "改logo": "Tweaking logos",
    "80%的时间花在这种纯执行上": "80% of their time was spent on pure execution",
    "现在AI接手了": "Now AI has taken over",
    "3秒出100张图": "Generating 100 images in 3 seconds",
    "那设计师呢": "So what about the designer",
    "不会被替代": "They won't be replaced",
    "但他得变成创意总监": "But they have to become a creative director",
    "他的价值不再是画得好": "Their value is no longer about drawing well",
    "是知道哪个画得好": "It's about knowing which one is good",
    "为什么这个对客户有用": "Why this works for the client",
    "他得懂用户": "They need to understand users",
    "懂品牌": "Understand branding",
    "懂转化": "Understand conversion",
    "懂市场": "Understand the market",
    "这些AI还干不了": "These are things AI still can't do",
    "升级后的设计师": "The upgraded designer",
    "工资从一个月8000涨到4万": "Went from 8000 a month to 40000",
    "被替代的设计师呢": "And the replaced designer",
    "月薪从8000直接掉到0": "Their monthly salary went from 8000 straight to zero",
    "同一个工种": "Same job title",
    "同一个公司": "Same company",
    "同一年": "Same year",
    "两种命运": "Two completely different fates",
    "差别在哪": "What's the difference",
    "差别在你过去5年": "The difference is in your past 5 years",
    "是只在低头切图": "Were you just head down slicing images",
    "还是抬头看了一下整个游戏": "Or did you look up and see the whole game",
    "我再给你一组数据": "Let me give you another set of data",
    "LinkedIn2025年职位报告": "LinkedIn's 2025 jobs report",
    "过去12个月里": "In the past 12 months",
    "初级开头的岗位招聘量同比下跌31%": "Job postings for junior-level positions dropped 31% year over year",
    "而主管/总监开头的岗位招聘量": "But postings for manager and director level positions",
    "同比涨了22%": "Went up 22% year over year",
    "中间的中级岗位呢": "What about mid-level positions in between",
    "基本持平": "Roughly flat",
    "你看出问题了吗": "Do you see the problem",
    "AI不是均匀地裁人": "AI doesn't cut jobs evenly",
    "它在掏空金字塔的底层": "It's hollowing out the bottom of the pyramid",
    "垫高金字塔的顶层": "And raising the top of the pyramid",
    "底层的人没机会上去了": "People at the bottom have no chance to move up",
    "顶层的人越来越值钱": "People at the top become more and more valuable",
    "你今天每多一个判断为什么的能力": "Every extra ability to judge why today",
    "就是在金字塔上往上爬一格": "Is you climbing one level up the pyramid",
    "我身边有个做文案的朋友": "I have a friend who's a copywriter",
    "去年公司裁了一半文案": "Last year his company laid off half the copywriting team",
    "他没被裁": "He wasn't laid off",
    "反而涨薪40%": "Instead he got a 40% raise",
    "我问他怎么做到的": "I asked him how he did it",
    "他说": "He said",
    "他从两年前就开始用AI写初稿": "He started using AI to write first drafts two years ago",
    "但所有为什么这么写的判断都自己做": "But all the judgment on why to write it this way he did himself",
    "老板看到的不是他写得多快": "His boss didn't see how fast he wrote",
    "是他能解释每一个决定": "His boss saw that he could explain every decision",
    "AI给他打下手": "AI was his assistant",
    "他给老板打方向": "He set the direction for his boss",
    "这就是互补效应的本质": "This is the essence of the complementarity effect",
    "你和AI不是替代关系": "You and AI are not in a substitution relationship",
    "是分工关系": "You're in a division of labor relationship",
    "替代效应和互补效应": "The substitution effect and complementarity effect",
    "决定你工资的方向": "Determine the direction of your salary",
    "它们的分界线": "The dividing line between them",
    "就一句话": "Is just one sentence",
    "你做的事是听话执行": "Is what you do just obedient execution",
    "还是判断为什么": "Or are you judging why",
    "回到主线": "Back to the main point",
    "经济学家大卫·李嘉图提出过一个理论": "200 years ago economist David Ricardo proposed a theory",
    "叫比较优势": "Called comparative advantage",
    "什么意思": "What does it mean",
    "哪怕一件事AI做得比你好": "Even if AI does something better than you",
    "只要你做得比别的事更好": "As long as you do it better than your other tasks",
    "你就还有价值": "You still have value",
    "我给你举个例子": "Let me give you an example",
    "假设AI写代码比你快10倍": "Say AI writes code 10 times faster than you",
    "但AI跟客户聊需求的时候": "But when AI talks to clients about requirements",
    "会出错": "It makes mistakes",
    "那你的价值就转向懂客户": "Then your value shifts to understanding clients",
    "懂产品那一面": "And understanding the product side",
    "你不跟AI比写代码": "You don't compete with AI on writing code",
    "你比的是什么代码值得写": "You compete on what code is worth writing",
    "这就是比较优势": "This is comparative advantage",
    "它告诉你一个真相": "It tells you a truth",
    "你不需要在所有事情上都打败AI": "You don't need to beat AI at everything",
    "你只需要在AI最弱": "You just need to find where AI is weakest",
    "人类最强的那个地带": "And humans are strongest",
    "建立你不可替代的位置": "And build your irreplaceable position there",
    "那AI最弱的地带在哪": "So where is AI weakest",
    "我给你列3个": "Let me list 3 areas",
    "第一个": "First",
    "跨学科判断": "Cross-disciplinary judgment",
    "需要同时调用心理学": "Tasks that require simultaneously drawing on psychology",
    "商业": "Business",
    "技术": "Technology",
    "人文知识做综合判断的事": "And humanities knowledge to make comprehensive judgments",
    "AI可以分别做这些": "AI can do each of these separately",
    "但综合起来": "But when combined",
    "它没内核": "It has no core understanding",
    "第二个": "Second",
    "复杂人际信任": "Complex interpersonal trust",
    "谈判": "Negotiation",
    "销售": "Sales",
    "管理": "Management",
    "教育": "Education",
    "心理疏导": "Psychological counseling",
    "任何需要看着对方眼睛建立信任的事": "Anything that requires looking someone in the eye to build trust",
    "AI干不了": "AI can't do it",
    "人是被人说服的": "People are persuaded by people",
    "不是被算法说服的": "Not by algorithms",
    "第三个": "Third",
    "高责任决策": "High-stakes decision making",
    "医生开刀": "Surgeons performing operations",
    "法官判案": "Judges ruling on cases",
    "CEO定战略": "CEOs setting strategy",
    "这些事出了问题要担责的": "When things go wrong someone has to take responsibility",
    "没人敢交给AI": "Nobody dares hand these over to AI",
    "只要你的工作能往这3个方向之一靠": "As long as your work leans toward any of these 3 directions",
    "你就在AI的射程之外": "You're out of AI's range",
    "但反过来": "But conversely",
    "如果你的工作是流程化": "If your work is process-driven",
    "规则化": "Rule-based",
    "可重复": "Repeatable",
    "你就在AI的瞄准镜里": "You're in AI's crosshairs",
    "你今天还没被裁": "You haven't been laid off today",
    "不是因为你强": "Not because you're strong",
    "是因为你的老板还没看清楚账": "It's because your boss hasn't figured out the math yet",
    "讲了这么多": "So much said",
    "怎么办": "What should you do",
    "我给你3个具体方法": "I'll give you 3 specific methods",
    "从今天开始用": "Start using them today",
    "第一个方法": "Method one",
    "叫AI杠杆法": "The AI leverage method",
    "不要把AI当对手": "Don't treat AI as an opponent",
    "当工具": "Treat it as a tool",
    "每个工作流": "For every workflow",
    "都问自己一句话": "Ask yourself one question",
    "哪一段我可以让AI干": "Which parts can I let AI handle",
    "哪一段必须我自己干": "Which parts must I do myself",
    "让AI干的部分": "The parts AI can handle",
    "立刻交出去": "Hand them over immediately",
    "省下来的时间": "The time you save",
    "不是去摸鱼": "Isn't for slacking off",
    "是去做更高阶的事": "It's for doing higher-level work",
    "举个例子": "For example",
    "一个市场经理": "A marketing manager",
    "本来一周做20份报表": "Used to spend a week making 20 reports",
    "用了AI之后": "After using AI",
    "一周20份报表只要1天": "20 reports now take just 1 day",
    "剩下的4天去干嘛": "What to do with the remaining 4 days",
    "去研究客户": "Go study clients",
    "去做行业分析": "Do industry analysis",
    "去给老板提战略建议": "Give the boss strategic advice",
    "老板看到他从做表的变成出主意的": "The boss sees him go from a report maker to an idea person",
    "下一个升职名单上就是他": "He's the next one on the promotion list",
    "第二个方法": "Method two",
    "叫不可替代清单": "The irreplaceability checklist",
    "每3个月做一次": "Do this once every 3 months",
    "写下你过去3个月做的所有事": "Write down everything you did in the past 3 months",
    "逐条问": "Go through each item and ask",
    "这件事AI能不能干": "Can AI do this",
    "能干的": "If yes",
    "标红": "Mark it red",
    "不能干的": "If no",
    "标绿": "Mark it green",
    "红色越多": "The more red you have",
    "你越危险": "The more danger you're in",
    "绿色越多": "The more green you have",
    "你越安全": "The safer you are",
    "然后想办法": "Then find a way",
    "把红色的活外包给AI": "Outsource the red tasks to AI",
    "把绿色的活做厚做深": "And make the green tasks deeper and stronger",
    "这是你的不可替代度": "This is your irreplaceability score",
    "它不是岗位决定的": "It's not determined by your job title",
    "是你每天的选择决定的": "It's determined by your daily choices",
    "第三个方法": "Method three",
    "叫向上半步法": "The step-up method",
    "如果你是初级": "If you're at a junior level",
    "别只想着把当前活干好": "Don't just think about doing your current job well",
    "抬头看你的上级在干什么": "Look up and see what your manager is doing",
    "他做的判断": "The judgments they make",
    "他对接的人": "The people they connect with",
    "他思考的问题": "The problems they think about",
    "你能不能慢慢承接一点": "Can you gradually take on some of that",
    "承接一点": "Take on just a little",
    "你就向AI替代不了的那条线": "And you move one step toward the line that AI can't cross",
    "往上半步": "Moving half a step up",
    "10年下来": "Over 10 years",
    "你会发现": "You'll find that",
    "那些踏踏实实只把本职做好的同事": "Those colleagues who only focused on doing their core job well",
    "被AI裁了": "Got replaced by AI",
    "那些老想着多承担一点的同事": "Those who always wanted to take on more",
    "被提拔成你的同事的同事": "Got promoted to manage the colleagues who didn't",
    "我给你模拟一个场景": "Let me simulate a scenario for you",
    "你是一个28岁的运营": "You're a 28-year-old operations person",
    "做了5年公众号编辑": "Who's been a WeChat editor for 5 years",
    "每天的工作是排版": "Your daily work is formatting",
    "配图": "Adding images",
    "改错字": "Fixing typos",
    "发文": "Publishing posts",
    "80%的时间在执行": "80% of your time is pure execution",
    "突然有一天": "Then one day",
    "老板说要降本增效": "The boss says we need to cut costs and boost efficiency",
    "先砍编辑岗": "Editor positions are first on the chopping block",
    "你怎么办": "What do you do",
    "第一步": "Step one",
    "立刻盘点你的工作里": "Immediately audit your work",
    "AI能干的部分": "For the parts AI can handle",
    "排版": "Formatting",
    "配图": "Image sourcing",
    "初步改错字": "Basic typo fixing",
    "发文": "Publishing",
    "AI都能干": "AI can do all of these",
    "剩下的判断什么内容值得发": "What remains is judging what content is worth publishing",
    "为什么这条会火": "Why a particular post will go viral",
    "怎么跟用户互动": "How to engage with users",
    "AI还干不了": "AI still can't do these",
    "第二步": "Step two",
    "把这80%交给AI": "Hand that 80% to AI",
    "自己花时间研究第二部分": "Spend your own time studying the second part",
    "研究3个月": "After 3 months of study",
    "你成了团队里懂内容": "You become the person in the team who understands content",
    "懂用户": "Understands users",
    "懂数据的那个人": "And understands data",
    "第三步": "Step three",
    "跟老板谈": "Talk to your boss",
    "我不要做编辑了": "I don't want to be an editor anymore",
    "我要做内容主理人": "I want to be a content lead",
    "带着AI": "Armed with AI",
    "一个人做之前5个人的活": "One person doing the work of 5 people before",
    "成本省给公司": "Saving costs for the company",
    "价值变到自己身上": "And keeping the value for yourself",
    "这就是从被裁那批到涨薪那批的全过程": "This is the complete process from the laid-off group to the raise group",
    "不需要你换工作": "You don't need to change jobs",
    "不需要你跳槽": "You don't need to job hop",
    "不需要你重新读书": "You don't need to go back to school",
    "需要的只是": "All you need is",
    "你今天就开始重新看自己的工作": "To start rethinking your work today",
    "其实关于AI和你的工资": "Actually about AI and your salary",
    "最核心的真相只有一句": "The core truth comes down to just one sentence",
    "AI不会消灭工作": "AI won't eliminate jobs",
    "AI会消灭工资低的工人": "AI will eliminate low-wage workers",
    "但同时": "But at the same time",
    "AI也会创造前所未有高薪的人": "AI will also create unprecedentedly high-earning people",
    "你站在哪一边": "Which side you stand on",
    "不取决于AI": "Doesn't depend on AI",
    "取决于你今天的选择": "It depends on your choice today",
    "最后送你一句话": "One last thing for you",
    "未来5年": "In the next 5 years",
    "被裁掉的人不是输给了AI": "The people who get laid off won't lose to AI",
    "是输给了": "They'll lose to",
    "比他更早学会用AI的同事": "Colleagues who learned to use AI earlier than them",
    "如果今天这条视频对你有启发": "If today's video inspired you",
    "点个关注": "Hit subscribe",
    "我每周讲一个经济学故事": "I share one economics story every week",
    "帮你看穿那些每天都在踩": "To help you see through the thinking traps",
    "却从来没注意到的思维陷阱": "You step on every day without even noticing",
    "你今天每多让AI干一件事": "Every extra task you let AI handle today",
    "未来都会多一份不被替代的底气": "Will give you more confidence in being irreplaceable in the future",
    "我们下期见": "See you next time",
}

# Build output
output_lines = []
for idx, (num, timestamp, text) in enumerate(entries, 1):
    cn_text = remove_cn_punctuation(text.strip())
    
    # Find translation - try exact match first, then check if text is a substring of a key
    en_text = translations.get(text.strip())
    if not en_text:
        # Try to find in translations by stripped version
        for key, val in translations.items():
            if key.strip() == text.strip():
                en_text = val
                break
    if not en_text:
        en_text = f"[NEEDS TRANSLATION: {text.strip()}]"
        print(f"Missing translation for entry {num}: {text.strip()}")
    
    # Remove trailing punctuation from English
    en_text = en_text.rstrip('.,;:!?')
    
    output_lines.append(f"{num}")
    output_lines.append(timestamp)
    output_lines.append(cn_text)
    output_lines.append(en_text)
    output_lines.append("")

output_path = r'E:\视频脚本\进行中\04-AI替你工作8小时你的工资涨还是跌\AI工作8小时_双语.srt'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(output_lines))

print(f"\nDone! Wrote {len(entries)} entries to {output_path}")
